//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Core.Measurement {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DecimalUnitPrefixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DecimalUnitPrefixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Core.Measurement.DecimalUnitPrefixResources", typeof(DecimalUnitPrefixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Compact00 {
            get {
                return ResourceManager.GetString("Compact00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to da.
        /// </summary>
        internal static string Compact01 {
            get {
                return ResourceManager.GetString("Compact01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        internal static string Compact02 {
            get {
                return ResourceManager.GetString("Compact02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to k.
        /// </summary>
        internal static string Compact03 {
            get {
                return ResourceManager.GetString("Compact03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M.
        /// </summary>
        internal static string Compact06 {
            get {
                return ResourceManager.GetString("Compact06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to G.
        /// </summary>
        internal static string Compact09 {
            get {
                return ResourceManager.GetString("Compact09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T.
        /// </summary>
        internal static string Compact12 {
            get {
                return ResourceManager.GetString("Compact12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.
        /// </summary>
        internal static string Compact15 {
            get {
                return ResourceManager.GetString("Compact15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E.
        /// </summary>
        internal static string Compact18 {
            get {
                return ResourceManager.GetString("Compact18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z.
        /// </summary>
        internal static string Compact21 {
            get {
                return ResourceManager.GetString("Compact21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y.
        /// </summary>
        internal static string Compact24 {
            get {
                return ResourceManager.GetString("Compact24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to d.
        /// </summary>
        internal static string CompactM01 {
            get {
                return ResourceManager.GetString("CompactM01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c.
        /// </summary>
        internal static string CompactM02 {
            get {
                return ResourceManager.GetString("CompactM02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.
        /// </summary>
        internal static string CompactM03 {
            get {
                return ResourceManager.GetString("CompactM03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to µ.
        /// </summary>
        internal static string CompactM06 {
            get {
                return ResourceManager.GetString("CompactM06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to n.
        /// </summary>
        internal static string CompactM09 {
            get {
                return ResourceManager.GetString("CompactM09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p.
        /// </summary>
        internal static string CompactM12 {
            get {
                return ResourceManager.GetString("CompactM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to f.
        /// </summary>
        internal static string CompactM15 {
            get {
                return ResourceManager.GetString("CompactM15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a.
        /// </summary>
        internal static string CompactM18 {
            get {
                return ResourceManager.GetString("CompactM18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.
        /// </summary>
        internal static string CompactM21 {
            get {
                return ResourceManager.GetString("CompactM21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to y.
        /// </summary>
        internal static string CompactM24 {
            get {
                return ResourceManager.GetString("CompactM24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string Full00 {
            get {
                return ResourceManager.GetString("Full00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deca.
        /// </summary>
        internal static string Full01 {
            get {
                return ResourceManager.GetString("Full01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hecto.
        /// </summary>
        internal static string Full02 {
            get {
                return ResourceManager.GetString("Full02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilo.
        /// </summary>
        internal static string Full03 {
            get {
                return ResourceManager.GetString("Full03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mega.
        /// </summary>
        internal static string Full06 {
            get {
                return ResourceManager.GetString("Full06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giga.
        /// </summary>
        internal static string Full09 {
            get {
                return ResourceManager.GetString("Full09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tera.
        /// </summary>
        internal static string Full12 {
            get {
                return ResourceManager.GetString("Full12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peta.
        /// </summary>
        internal static string Full15 {
            get {
                return ResourceManager.GetString("Full15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exa.
        /// </summary>
        internal static string Full18 {
            get {
                return ResourceManager.GetString("Full18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zetta.
        /// </summary>
        internal static string Full21 {
            get {
                return ResourceManager.GetString("Full21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yotta.
        /// </summary>
        internal static string Full24 {
            get {
                return ResourceManager.GetString("Full24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deci.
        /// </summary>
        internal static string FullM01 {
            get {
                return ResourceManager.GetString("FullM01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centi.
        /// </summary>
        internal static string FullM02 {
            get {
                return ResourceManager.GetString("FullM02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Milli.
        /// </summary>
        internal static string FullM03 {
            get {
                return ResourceManager.GetString("FullM03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Micro.
        /// </summary>
        internal static string FullM06 {
            get {
                return ResourceManager.GetString("FullM06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nano.
        /// </summary>
        internal static string FullM09 {
            get {
                return ResourceManager.GetString("FullM09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pico.
        /// </summary>
        internal static string FullM12 {
            get {
                return ResourceManager.GetString("FullM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Femto.
        /// </summary>
        internal static string FullM15 {
            get {
                return ResourceManager.GetString("FullM15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atto.
        /// </summary>
        internal static string FullM18 {
            get {
                return ResourceManager.GetString("FullM18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zepto.
        /// </summary>
        internal static string FullM21 {
            get {
                return ResourceManager.GetString("FullM21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yocto.
        /// </summary>
        internal static string FullM24 {
            get {
                return ResourceManager.GetString("FullM24", resourceCulture);
            }
        }
    }
}
