//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo.Files.Authorization.Presentations.WebApi {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WebApiResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebApiResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Demo.Files.Authorization.Presentations.WebApi.WebApiResources", typeof(WebApiResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more internal server errors occurred..
        /// </summary>
        internal static string Error_InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("Error_InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already activated..
        /// </summary>
        internal static string UserError_AlreadyActive {
            get {
                return ResourceManager.GetString("UserError_AlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is already deactivated..
        /// </summary>
        internal static string UserError_AlreadyDeactivated {
            get {
                return ResourceManager.GetString("UserError_AlreadyDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not active..
        /// </summary>
        internal static string UserError_Deactivated {
            get {
                return ResourceManager.GetString("UserError_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty username is not supported..
        /// </summary>
        internal static string UserError_DisplayNameEmpty {
            get {
                return ResourceManager.GetString("UserError_DisplayNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username format..
        /// </summary>
        internal static string UserError_DisplayNameInvalidFormat {
            get {
                return ResourceManager.GetString("UserError_DisplayNameInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is too long..
        /// </summary>
        internal static string UserError_DisplayNameTooLong {
            get {
                return ResourceManager.GetString("UserError_DisplayNameTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in the username..
        /// </summary>
        internal static string UserError_DisplayNameUnsupportedCharacters {
            get {
                return ResourceManager.GetString("UserError_DisplayNameUnsupportedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user does not own this resource..
        /// </summary>
        internal static string UserError_DoesNotOwnResource {
            get {
                return ResourceManager.GetString("UserError_DoesNotOwnResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this email already exists..
        /// </summary>
        internal static string UserError_EmailConflict {
            get {
                return ResourceManager.GetString("UserError_EmailConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty email is not allowed..
        /// </summary>
        internal static string UserError_EmailEmpty {
            get {
                return ResourceManager.GetString("UserError_EmailEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format..
        /// </summary>
        internal static string UserError_EmailInvalidFormat {
            get {
                return ResourceManager.GetString("UserError_EmailInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in the email..
        /// </summary>
        internal static string UserError_EmailUnsupportedCharacters {
            get {
                return ResourceManager.GetString("UserError_EmailUnsupportedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported email provider..
        /// </summary>
        internal static string UserError_EmailUnsupportedProvider {
            get {
                return ResourceManager.GetString("UserError_EmailUnsupportedProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User data is corrupted..
        /// </summary>
        internal static string UserError_InvalidHistory {
            get {
                return ResourceManager.GetString("UserError_InvalidHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no such user..
        /// </summary>
        internal static string UserError_NotExists {
            get {
                return ResourceManager.GetString("UserError_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user has already been changed..
        /// </summary>
        internal static string UserError_Outdated {
            get {
                return ResourceManager.GetString("UserError_Outdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An empty password is not supported..
        /// </summary>
        internal static string UserError_PasswordEmpty {
            get {
                return ResourceManager.GetString("UserError_PasswordEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password length..
        /// </summary>
        internal static string UserError_PasswordInvalidLength {
            get {
                return ResourceManager.GetString("UserError_PasswordInvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters in the password..
        /// </summary>
        internal static string UserError_PasswordUnsupportedCharacters {
            get {
                return ResourceManager.GetString("UserError_PasswordUnsupportedCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource has already been received..
        /// </summary>
        internal static string UserError_ResourceAlreadyAcquired {
            get {
                return ResourceManager.GetString("UserError_ResourceAlreadyAcquired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such a resource already exists..
        /// </summary>
        internal static string UserError_ResourceConflict {
            get {
                return ResourceManager.GetString("UserError_ResourceConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This resource was not requested..
        /// </summary>
        internal static string UserError_ResourceNotRequested {
            get {
                return ResourceManager.GetString("UserError_ResourceNotRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user with this username already exists..
        /// </summary>
        internal static string UserError_UsernameConflict {
            get {
                return ResourceManager.GetString("UserError_UsernameConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name format..
        /// </summary>
        internal static string UserError_UsernameFormat {
            get {
                return ResourceManager.GetString("UserError_UsernameFormat", resourceCulture);
            }
        }
    }
}
